### ISSUE TITLE
streamset通过jdbc producr 往clickhouse 写数据问题

### ISSUE THREAD

**Issue by zjp123456** [anjia0532/anjia0532.github.io#2]
请问一下，我在你的这篇博客中看到，通过streamsets往clickhouse中同步数据，你有尝试过往clickhouse的分布式表中写吗？
目前我通过实践发现，往本地表写是可以的，往分布式表写会报错，如图
![image](https://user-images.githubusercontent.com/8458143/105320291-f67bdc80-5c00-11eb-87a6-59a6fa572b20.png)

https://anjia0532.github.io/2019/07/17/mysql-to-clickhouse/

**Comment by zjp123456** [comment]
报错信息：
JDBC_16 - Table 'ods_crm_f_follow' does not exist or PDB is incorrect. Make sure the correct PDB was specified

**Comment by anjia0532** [comment]
没有用到分布式表
